remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-remote-theme

title: Vehicle Recognizer
description: An image classification API that classifies 28 different types of vehicles commonly around the world.

author:
  name: Anis Taluqdar

# New style configuration
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author_profile: true
      share: true
      read_time: true
      comments: true

theme:
  fonts:
    body: "Arial, sans-serif"
    heading: "Georgia, serif"

  # Colors
  color_scheme: dark # or light
  accent_color: "#3498db" # Change this to your preferred accent color

  # Layout
  content_width: 800px
  header:
    background: "#2c3e50" # Change this to your preferred header background color
    text_color: "#ffffff" # Change this to your preferred header text color


